version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
        POSTGRES_DB: "slavadb"
        POSTGRES_USER: "slava"
        POSTGRES_PASSWORD: "slavapswd"
    ports:
      - "5432:5432"
      